### PR TITLE
Allowing buzz upgrade to recent version

### PR DESCRIPTION
**Pull request by anvyst**
Upgrading `kriswallsmith/Buzz` to `^0.15` that brings numerous patches to the package plus PSR-4 transition from PSR-0, as well as PHP7 compatibility

### CODE REVIEW

**Comment by sd-lueckel** [comment]
Thanks for the pull-request.

Unfortunately composer fails to install dependencies.
See https://scrutinizer-ci.com/g/solutionDrive/HipchatAPIv2Client/inspections/8a1c5fab-7e0c-46ab-8698-91d9907a8add
`composer install --ignore-platform-reqs --no-interaction --no-scripts --no-plugins inferred 10:02
The command produced no output for 600 seconds. You can increase this timeout by defining the "idle_timeout" modifier.
Loading composer repositories with package information
Updating dependencies (including require-dev)`

and https://insight.sensiolabs.com/projects/fe1dde4f-3158-45db-8f9a-315f97f2cd54/analyses/28
`Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 10 updates, 0 removals
  - Updating kriswallsmith/buzz (v0.10 => v0.15.2): Downloading (failed)
Downloading (failed)
Downloading (failed)
                                                                                                                                                                                    
  [Composer\Downloader\TransportException]                                                                                                                                          
  The "https://api.github.com/repos/kriswallsmith/Buzz/zipball/d0b82d8a6169276f91f445c26792ff4a2b11e831" file could not be downloaded: failed to open stream: HTTP request failed!  
                                                                                                                                                                                    

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...`

**Comment by anvyst** [comment]
@sd-lueckel composer issue could have been caused by composer infrastructure timeouts. Can you re-run the scrutinizer/sensiolabsinsight, just to make sure that upgrade runs smoothly?

**Comment by anvyst** [comment]
@sd-lueckel Travis fixed with recent patch (using dist install instead of `--prefer-source` for composer packages), which boosted build performance.

**Review by sd-lueckel — APPROVED** [review]

**Comment by sd-lueckel** [comment]
Thank you

**Comment by anvyst** [comment]
@sd-lueckel you're welcome! If by any chance you can tag this as bugfix release that would be awesome, so I could use your package instead of the outdated (custom patched) version from `gorkalaucirica/hipchat-v2-api-client` :)

**Comment by sd-lueckel** [comment]
@anvyst no problem! I tagged v2.0.1 as a new release version!

**Pull request merged**
